### ISSUE TITLE
Why does my overview() load forever?

### ISSUE THREAD

**Issue by gitgithan** [zilliztech/feder#71]
In colab, visualizing both hnsw and faiss using my own index with overview or searchRandTestVec shows the cell has finished running but the blue spinning circle goes on forever on a white output. 

The same notebook can show the examples from https://colab.research.google.com/drive/12L_oJPR-yFDlORpPondsqGNTPVsSsUwi#scrollTo=N3qqBAYxYcbt though. 

Is the problem with the index used? 
I tried reducing the dimensionality to 5, even lower than the 10 in the example but it still loads forever.

How to investigate how the indexes at
```
hnswSource = 'hnswlib'
hnswIndexFile = 'https://assets.zilliz.com/hnswlib_hnsw_voc_17k_1f1dfd63a9.index'

ivfflatSource = 'faiss'
ivfflatIndexFile = 'https://assets.zilliz.com/faiss_ivf_flat_voc_17k_ab112eec72.index'
```
were built? 

I tried to find the data using
```
import requests

hnswIndexFile = 'https://assets.zilliz.com/hnswlib_hnsw_voc_17k_1f1dfd63a9.index'
localFilename = 'hnswlib_hnsw_voc_17k_1f1dfd63a9.index'

response = requests.get(hnswIndexFile)
with open(localFilename, 'wb') as f:
    f.write(response.content)

p = hnswlib.Index(space='l2',dim=10)
p.load_index(localFilename)
p.get_items()
```
but got empty list. 
I was expecting get_items() to show the data added to the index

**Comment by alwayslove2013** [comment]
```python
federPy = FederPy(hnswIndexFile, hnswSource, **hnswViewParams)
```
Note that the index file required by `federPy` cannot be a local file. You can use `python http.server` to build a simple http server.

The reason for this is that the actual output of `federPy` is an `html` file like [that](https://colab.research.google.com/drive/12L_oJPR-yFDlORpPondsqGNTPVsSsUwi#scrollTo=wfpUa0E_922C&line=1&uniqifier=1), which goes through the browser to fetch the index file and render it using `javascript`. There are many security restrictions on browsers fetching local files directly.

In addition, place the index file on the web in order to facilitate the sharing of visualizations created by `feder`.

**Comment by gitgithan** [comment]
Any publicly accessible url is fine right? 
I upload mine to s3 with public access but both hnsw/faiss still shows blank output

https://federindexes.s3.ap-southeast-1.amazonaws.com/faiss.index
https://federindexes.s3.ap-southeast-1.amazonaws.com/hnsw.index

**Comment by alwayslove2013** [comment]
It seem that your s3 file does not allow cross-domain access.

**Comment by gitgithan** [comment]
Thanks looks like the visualizations are showing after allowing all origins in CORS policy. 
However imageUrls don't show. Must images be from public urls too?
